# Generated by Django 5.2.3 on 2025-06-17 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=1024)),
                ('structure_hash', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'code_files',
            },
        ),
        migrations.CreateModel(
            name='CodeClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_line', models.IntegerField()),
                ('end_line', models.IntegerField()),
                ('structure_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('code_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='repositories.codefile')),
            ],
            options={
                'db_table': 'code_classes',
            },
        ),
        migrations.CreateModel(
            name='CodeSymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(blank=True, db_index=True, max_length=1024, null=True)),
                ('name', models.CharField(max_length=255)),
                ('start_line', models.IntegerField()),
                ('end_line', models.IntegerField()),
                ('content_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('documentation_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('documentation', models.TextField(blank=True, null=True)),
                ('code_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='methods', to='repositories.codeclass')),
                ('code_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='symbols', to='repositories.codefile')),
            ],
            options={
                'db_table': 'code_symbols',
            },
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=512, unique=True)),
                ('github_id', models.IntegerField(unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('INDEXING', 'Indexing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('root_merkle_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'repositories',
            },
        ),
        migrations.AddField(
            model_name='codefile',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='repositories.repository'),
        ),
        migrations.CreateModel(
            name='CodeDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_calls', to='repositories.codesymbol')),
                ('caller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_calls', to='repositories.codesymbol')),
            ],
            options={
                'db_table': 'code_dependencies',
                'unique_together': {('caller', 'callee')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='codefile',
            unique_together={('repository', 'file_path')},
        ),
    ]
