# Generated by Django 5.2.3 on 2025-06-17 19:22

from django.db import migrations
from ..operations import VectorExtension # Import our custom operation


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0001_initial'),
    ]

    operations = [
        VectorExtension(),
    ]
