# Generated by Django 5.2.3 on 2025-06-17 19:23

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0002_enable_vector_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesymbol',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
    ]
