# Generated by Django 5.2.3 on 2025-06-17 19:24

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0003_codesymbol_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codesymbol',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True),
        ),
    ]
