# Generated by Django 5.2.3 on 2025-06-19 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0004_alter_codesymbol_embedding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsyncTaskStatus',
            fields=[
                ('task_id', models.CharField(help_text='Celery task ID', max_length=255, primary_key=True, serialize=False, unique=True)),
                ('task_name', models.CharField(choices=[('BATCH_GENERATE_DOCS', 'Batch Generate Docstrings'), ('CREATE_BATCH_PR', 'Create Batch Pull Request'), ('PROCESS_REPOSITORY', 'Process Repository')], help_text='Identifier for the type of task', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('RETRY', 'Retry')], default='PENDING', max_length=20)),
                ('progress', models.PositiveIntegerField(default=0, help_text='Progress percentage (0-100), if applicable')),
                ('message', models.TextField(blank=True, help_text='Status message, error details, or success summary', null=True)),
                ('result_data', models.JSONField(blank=True, help_text='Structured result data, e.g., PR URL, counts', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repository', models.ForeignKey(blank=True, help_text='Associated repository, if applicable', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_statuses', to='repositories.repository')),
                ('user', models.ForeignKey(help_text='User who initiated the task', on_delete=django.db.models.deletion.CASCADE, related_name='task_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'async_task_statuses',
                'ordering': ['-created_at'],
            },
        ),
    ]
