# Generated by Django 5.2.3 on 2025-06-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0005_asynctaskstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesymbol',
            name='documentation_status',
            field=models.CharField(choices=[('NONE', 'No Documentation'), ('PENDING_REVIEW', 'AI Generated - Pending Review'), ('EDITED_PENDING_PR', 'Human Edited - Pending PR'), ('APPROVED_IN_PR', 'Approved - In PR'), ('MERGED', 'Merged in Source')], default='NONE', help_text='The review and approval status of the documentation.', max_length=20),
        ),
    ]
