# Generated by Django 5.2.3 on 2025-06-19 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0006_codesymbol_documentation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codesymbol',
            name='documentation_status',
            field=models.CharField(choices=[('NONE', 'No Documentation'), ('PENDING_REVIEW', 'AI Generated - Pending Review'), ('EDITED_PENDING_PR', 'Human Edited - Ready for PR'), ('STALE', 'Stale Documentation'), ('FRESH', 'Fresh Documentation')], default='NONE', help_text='The review and approval status of the documentation.', max_length=20),
        ),
    ]
