# Generated by Django 5.2.3 on 2025-06-19 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0008_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repository',
            options={'verbose_name_plural': 'Repositories'},
        ),
        migrations.AddField(
            model_name='repository',
            name='last_processed',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last successful processing by the Celery task.', null=True),
        ),
    ]
