# Generated by Django 5.2.3 on 2025-06-21 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0009_alter_repository_options_repository_last_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesymbol',
            name='is_orphan',
            field=models.BooleanField(db_index=True, default=False, help_text='True if this symbol is not called by any other symbol in the repository.'),
        ),
    ]
