# Generated by Django 5.2.3 on 2025-06-21 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0010_codesymbol_is_orphan'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesymbol',
            name='cyclomatic_complexity',
            field=models.PositiveIntegerField(blank=True, help_text='Calculated cyclomatic complexity of the symbol', null=True),
        ),
        migrations.AddField(
            model_name='codesymbol',
            name='loc',
            field=models.PositiveIntegerField(blank=True, help_text='Lines of Code (non-empty, non-comment lines within the symbol body)', null=True),
        ),
    ]
