# Generated by Django 5.2.3 on 2025-06-21 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0011_codesymbol_cyclomatic_complexity_codesymbol_loc'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbeddingBatchJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(db_index=True, help_text='OpenAI Batch API Job ID', max_length=100, unique=True)),
                ('input_file_id', models.CharField(help_text='OpenAI File ID for the input batch .jsonl file', max_length=100)),
                ('output_file_id', models.CharField(blank=True, help_text='OpenAI File ID for the output results .jsonl file', max_length=100, null=True)),
                ('error_file_id', models.CharField(blank=True, help_text='OpenAI File ID for the error details .jsonl file', max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending_submission', 'Pending Submission to OpenAI'), ('validating', 'Validating'), ('failed_validation', 'Failed Validation'), ('in_progress', 'In Progress'), ('finalizing', 'Finalizing'), ('completed', 'Completed by OpenAI'), ('failed', 'Failed by OpenAI'), ('expired', 'Expired by OpenAI'), ('cancelling', 'Cancelling'), ('cancelled', 'Cancelled'), ('results_processing', 'Processing Results'), ('results_processed', 'Results Processed in DB'), ('results_failed_to_process', 'Failed to Process Results')], db_index=True, default='pending_submission', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_to_openai_at', models.DateTimeField(blank=True, null=True)),
                ('openai_completed_at', models.DateTimeField(blank=True, null=True)),
                ('results_processed_at', models.DateTimeField(blank=True, null=True)),
                ('openai_metadata', models.JSONField(blank=True, help_text='Metadata from OpenAI Batch object', null=True)),
                ('custom_metadata', models.JSONField(blank=True, help_text='Custom metadata for this job', null=True)),
                ('error_details', models.TextField(blank=True, help_text='Details of any processing errors', null=True)),
                ('repository', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='embedding_batch_jobs', to='repositories.repository')),
            ],
            options={
                'verbose_name': 'Embedding Batch Job',
                'verbose_name_plural': 'Embedding Batch Jobs',
                'db_table': 'embedding_batch_jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
