# Generated by Django 5.2.3 on 2025-06-22 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0012_embeddingbatchjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit_hash', models.CharField(db_index=True, max_length=40)),
                ('insight_type', models.CharField(choices=[('SYMBOL_ADDED', 'Symbol Added'), ('SYMBOL_REMOVED', 'Symbol Removed'), ('SYMBOL_MODIFIED', 'Symbol Modified'), ('DEPENDENCY_ADDED', 'Dependency Added'), ('DEPENDENCY_REMOVED', 'Dependency Removed')], db_index=True, max_length=30)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict, null=True)),
                ('is_resolved', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_symbol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insights', to='repositories.codesymbol')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='repositories.repository')),
            ],
            options={
                'db_table': 'repository_insights',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['repository', 'commit_hash'], name='repository__reposit_7bf3c6_idx')],
            },
        ),
    ]
