# Generated by Django 5.2.3 on 2025-06-23 06:46

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0013_insight'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_type', models.CharField(choices=[('MODULE_README', 'Module README'), ('CLASS_SUMMARY', 'Class Summary'), ('SYMBOL_DOCSTRING', 'Symbol Docstring'), ('SYMBOL_SOURCE', 'Symbol Source Code')], max_length=20)),
                ('content', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536)),
                ('related_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='repositories.codeclass')),
                ('related_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='repositories.codefile')),
                ('related_symbol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='repositories.codesymbol')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_chunks', to='repositories.repository')),
            ],
            options={
                'db_table': 'knowledge_chunks',
                'indexes': [pgvector.django.indexes.HnswIndex(fields=['embedding'], name='knowledge_embedding_hnsw_l2_idx', opclasses=['vector_l2_ops'])],
            },
        ),
    ]
