# Generated by Django 5.2.3 on 2025-06-23 07:04

import django.utils.timezone
import pgvector.django.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0014_knowledgechunk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='knowledgechunk',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='knowledgechunk',
            name='knowledge_embedding_hnsw_l2_idx',
        ),
        migrations.AddField(
            model_name='knowledgechunk',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='knowledgechunk',
            name='chunk_type',
            field=models.CharField(choices=[('SYMBOL_DOCSTRING', 'Symbol Docstring'), ('SYMBOL_SOURCE', 'Symbol Source Code')], db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='knowledgechunk',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='knowledge_embedding_hnsw_l2_idx', opclasses=['vector_l2_ops']),
        ),
    ]
