# Generated by Django 5.2.3 on 2025-06-23 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0015_alter_knowledgechunk_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='embeddingbatchjob',
            name='job_type',
            field=models.CharField(choices=[('SYMBOL_EMBEDDING', 'Symbol Embedding'), ('INSIGHT_EMBEDDING', 'Insight Embedding')], default='SYMBOL_EMBEDDING', help_text='The type of content this batch job is for.', max_length=20),
        ),
    ]
