# Generated by Django 5.2.3 on 2025-06-23 09:47

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0016_embeddingbatchjob_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgechunk',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True),
        ),
    ]
