# Generated by Django 5.2.3 on 2025-06-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0017_alter_knowledgechunk_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embeddingbatchjob',
            name='job_type',
            field=models.CharField(choices=[('SYMBOL_EMBEDDING', 'Symbol Embedding'), ('KNOWLEDGE_CHUNK_EMBEDDING', 'Knowledge Chunk Embedding')], default='SYMBOL_EMBEDDING', help_text='The type of content this batch job is for.', max_length=30),
        ),
    ]
