# Generated by Django 5.2.3 on 2025-06-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0018_alter_embeddingbatchjob_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='embeddingbatchjob',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the job was confirmed as completed by our poller.', null=True),
        ),
        migrations.AlterField(
            model_name='embeddingbatchjob',
            name='output_file_id',
            field=models.CharField(blank=True, help_text='The ID of the output file from a completed OpenAI job.', max_length=100, null=True),
        ),
    ]
