# Generated by Django 5.2.3 on 2025-07-02 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0019_embeddingbatchjob_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codefile',
            name='imports',
            field=models.JSONField(blank=True, help_text='A list of modules imported in this file, extracted by the parser.', null=True),
        ),
    ]
