# Generated by Django 5.2.3 on 2025-06-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0019_embeddingbatchjob_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='default_branch',
            field=models.CharField(default='main', max_length=100),
        ),
    ]
