# Generated by Django 5.2.3 on 2025-07-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0020_codefile_imports'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeclass',
            name='summary',
            field=models.TextField(blank=True, help_text="A one-sentence summary of the class's purpose, generated by Helix AI.", null=True),
        ),
    ]
