# Generated by Django 5.2.3 on 2025-07-02 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0020_repository_default_branch'),
        ('repositories', '0021_codeclass_summary'),
    ]

    operations = [
    ]
