# Generated by Django 5.2.3 on 2025-07-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0022_merge_20250702_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeclass',
            name='generated_summary_md',
            field=models.TextField(blank=True, help_text='The full, detailed markdown summary of the class, generated by Helix AI.', null=True),
        ),
        migrations.AlterField(
            model_name='codeclass',
            name='summary',
            field=models.CharField(blank=True, help_text="A concise, one-sentence summary of the class's purpose, generated by Helix AI.", max_length=512, null=True),
        ),
    ]
