# Generated by Django 5.2.3 on 2025-07-02 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0023_codeclass_generated_summary_md_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleDocumentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_path', models.CharField(db_index=True, max_length=1024)),
                ('content_md', models.TextField()),
                ('last_generated_at', models.DateTimeField(auto_now=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_docs', to='repositories.repository')),
            ],
            options={
                'ordering': ['-last_generated_at'],
                'unique_together': {('repository', 'module_path')},
            },
        ),
    ]
