# Generated by Django 5.2.3 on 2025-07-02 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0024_moduledocumentation'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='moduledocumentation',
            table='module_documentation',
        ),
    ]
