# Generated by Django 5.2.3 on 2025-07-02 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0025_alter_moduledocumentation_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesymbol',
            name='existing_docstring',
            field=models.TextField(blank=True, help_text='The docstring that existed in the source code during the last scan.', null=True),
        ),
        migrations.AddField(
            model_name='codesymbol',
            name='signature_end_location',
            field=models.JSONField(blank=True, help_text="A JSON object with {'line': y, 'column': z} indicating where the function signature ends.", null=True),
        ),
        migrations.AlterField(
            model_name='asynctaskstatus',
            name='task_name',
            field=models.CharField(choices=[('BATCH_GENERATE_DOCS', 'Batch Generate Docstrings'), ('CREATE_BATCH_PR', 'Create Batch Pull Request'), ('PROCESS_REPOSITORY', 'Process Repository'), ('MODULE_WORKFLOW', 'Generate Module Documentation')], help_text='Identifier for the type of task', max_length=50),
        ),
        migrations.AlterField(
            model_name='knowledgechunk',
            name='chunk_type',
            field=models.CharField(choices=[('MODULE_README', 'Module README'), ('CLASS_SUMMARY', 'Class Summary'), ('SYMBOL_DOCSTRING', 'Symbol Docstring'), ('SYMBOL_SOURCE', 'Symbol Source Code')], db_index=True, max_length=20),
        ),
    ]
