# Generated by Django 5.2.3 on 2025-07-03 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0026_codesymbol_existing_docstring_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='documentation_coverage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='repository',
            name='orphan_symbol_count',
            field=models.IntegerField(default=0),
        ),
    ]
