# Generated by Django 5.2.3 on 2025-07-03 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0027_repository_documentation_coverage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_dependencies', to='repositories.repository')),
                ('source_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_dependencies', to='repositories.codefile')),
                ('target_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_dependencies', to='repositories.codefile')),
            ],
            options={
                'db_table': 'module_dependencies',
                'indexes': [models.Index(fields=['source_file'], name='module_depe_source__d9b21f_idx'), models.Index(fields=['target_file'], name='module_depe_target__154618_idx')],
                'unique_together': {('source_file', 'target_file')},
            },
        ),
    ]
