# Generated by Django 5.2.3 on 2025-07-05 15:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0030_alter_repository_organization_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='ai_requests_limit',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='organization',
            name='ai_requests_this_month',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='organization',
            name='last_usage_reset',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
