# Generated by Django 5.2.3 on 2025-07-08 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0031_organization_ai_requests_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='source_root',
            field=models.CharField(blank=True, default='.', help_text="The source root directory for Python imports, relative to the repo root (e.g., 'src', '.').", max_length=255),
        ),
    ]
