# Generated by Django 5.2.3 on 2025-07-08 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0032_repository_source_root'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCoverageReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit_hash', models.CharField(help_text='The commit hash this report is for.', max_length=40)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('overall_coverage', models.FloatField(help_text='Overall line rate (e.g., 0.95 for 95%).')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverage_reports', to='repositories.repository')),
            ],
            options={
                'db_table': 'test_coverage_reports',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='FileCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_rate', models.FloatField(help_text='Line rate for this file (e.g., 0.80 for 80%).')),
                ('covered_lines', models.JSONField(default=list, help_text='List of line numbers that were executed.')),
                ('missed_lines', models.JSONField(default=list, help_text='List of line numbers that were not executed.')),
                ('code_file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coverage_data', to='repositories.codefile')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_coverages', to='repositories.testcoveragereport')),
            ],
            options={
                'db_table': 'test_file_coverage',
                'unique_together': {('report', 'code_file')},
            },
        ),
    ]
