# Generated by Django 5.2.3 on 2025-07-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0033_testcoveragereport_filecoverage'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='commit_count',
            field=models.PositiveIntegerField(default=0, help_text='The total number of commits in the default branch.'),
        ),
        migrations.AddField(
            model_name='repository',
            name='contributor_count',
            field=models.PositiveIntegerField(default=0, help_text='The number of unique contributors to the repository.'),
        ),
        migrations.AddField(
            model_name='repository',
            name='primary_language',
            field=models.CharField(blank=True, help_text='The dominant programming language of the repository.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='size_kb',
            field=models.PositiveIntegerField(default=0, help_text='The size of the repository on disk in kilobytes.'),
        ),
    ]
