# Generated by Django 5.2.3 on 2025-07-20 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0034_repository_commit_count_repository_contributor_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embeddingbatchjob',
            name='batch_id',
            field=models.CharField(blank=True, db_index=True, help_text='OpenAI Batch API Job ID', max_length=100, null=True, unique=True),
        ),
    ]
