# Generated by Django 5.2.3 on 2025-09-11 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0002_add_local_repository_support'),
        ('repositories', '0035_alter_embeddingbatchjob_batch_id'),
    ]

    operations = [
    ]
