# Generated by Django 5.2.3 on 2025-07-05 15:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BetaInviteCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique, unguessable code for the invitation.', unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this code can still be used. Deactivate to disable it.')),
                ('uses', models.PositiveIntegerField(default=0, help_text='The number of times this code has been used.')),
                ('max_uses', models.PositiveIntegerField(default=1, help_text='The maximum number of times this code can be used.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional date when this invite code will expire.', null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin or system user who created the code.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Beta Invite Code',
                'verbose_name_plural': 'Beta Invite Codes',
                'db_table': 'beta_invite_codes',
            },
        ),
    ]
